### ISSUE TITLE
Am I allowed to push to this repository?

### ISSUE THREAD

**Issue by enocera** [NNPDF/pinecards#169]
I have generated the grid and the FK table for the EMC experiment, which was missing in theory 400. I'd like to push to a branch where I've written the relevant `metadata.txt` and `observable.yaml`. However, whn I try to do so, I receive the following message:
`remote: Permission to NNPDF/pinecards.git denied to enocera.`

**Comment by AleCandido** [comment]
This is weird, we just changed name to the former `runcards`. Everyone in NNPDF should be able to write to all repos...

**Comment by AleCandido** [comment]
This is what I see in the [Settings](https://github.com/NNPDF/pinecards/settings/access) tab (that you should be able to access as well):
![image](https://user-images.githubusercontent.com/10830876/210379872-64cd8a5d-3e47-4d82-a0fc-cbfadf6ef539.png)

**Comment by enocera** [comment]
Indeed, I saw that.

**Comment by enocera** [comment]
That's why I don't know what's going on.

**Comment by AleCandido** [comment]
Just to make sure is not a problem with the URL or something like, try to clone the repository from scratch (in a new location), and push something in the new clone.

**Comment by enocera** [comment]
Solved. I cloned the repo again and it worked.
